require('basic')
require('plugins')
require('keybindings')
require('colorscheme')
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
-- require("plugin-config.barbar")
require("plugin-config.lualine")
require("plugin-config.telescope")
require("plugin-config.dashboard")
require("plugin-config.project")
require("plugin-config.nvim-treesitter")
require("plugin-config.comment")
require("plugin-config.surround")
require("plugin-config.toggleterm")
require("plugin-config.nvim-autopairs")
require("plugin-config.indent-blankline")
require("plugin-config.gitsigns")
require("plugin-config.nvim-spectre")
require("plugin-config.nvim-colorizer")
require("plugin-config.which-key")
require("plugin-config.neoscroll")
require("plugin-config.hop")
require("plugin-config.spellsitter")
require("plugin-config.goto-preview")
require("plugin-config.symbols-outline")
require("plugin-config.marks")
require("plugin-config.harpoon")
require("plugin-config.diffview")
require("plugin-config.trouble")
-- require("plugin-config.nvim-transparent")
-- require("plugin-config.vim-visual-multi")
require("plugin-config.auto-session")
require("plugin-config.winbar")
require("lsp.setup")
require("lsp.cmp")
require("lsp.ui")
require("lsp.null-ls")
